/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg2_jamilgarcia;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JamilGarcía
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_MenuPartes = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_tamañoR = new javax.swing.JTextField();
        tf_marcaR = new javax.swing.JTextField();
        b_guardarR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_tamañoDD = new javax.swing.JTextField();
        tf_marcaDD = new javax.swing.JTextField();
        b_guardarDD = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_CapicidadB = new javax.swing.JTextField();
        tf_materialB = new javax.swing.JTextField();
        b_guardarB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_materialT = new javax.swing.JTextField();
        tf_colorT = new javax.swing.JTextField();
        b_guardarT = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_tipoP = new javax.swing.JTextField();
        chb_tactil = new javax.swing.JCheckBox();
        b_guardarP = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_nucleosPr = new javax.swing.JTextField();
        tf_velocidadPr = new javax.swing.JTextField();
        b_guardarPr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_TiempoE = new javax.swing.JTextField();
        jf_MenuComputadoras = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_NumeroSerieC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_añoC = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_colorC = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_materialC = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cb_RAM = new javax.swing.JComboBox<>();
        cb_DIscoD = new javax.swing.JComboBox<>();
        cb_Bateria = new javax.swing.JComboBox<>();
        cb_teclado = new javax.swing.JComboBox<>();
        cb_pantalla = new javax.swing.JComboBox<>();
        cb_procesador = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        b_listacomp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrden = new javax.swing.JTable();
        cb_tecnico = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cb_Computadoras = new javax.swing.JComboBox<>();
        b_modComps = new javax.swing.JButton();
        b_elimcomp = new javax.swing.JButton();
        b_ensamblarComp = new javax.swing.JButton();
        barra = new javax.swing.JProgressBar();
        jf_MenuTecnicos = new javax.swing.JFrame();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_nombreTec = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tf_edadTec = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        rd_M = new javax.swing.JRadioButton();
        rd_F = new javax.swing.JRadioButton();
        b_crearTec = new javax.swing.JButton();
        cb_tecnicos = new javax.swing.JComboBox<>();
        b_modTec = new javax.swing.JButton();
        b_EliminarTec = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        b_menupartes = new javax.swing.JButton();
        b_menuComps = new javax.swing.JButton();
        b_menuTecni = new javax.swing.JButton();

        jLabel4.setText("Tamaño:");

        jLabel5.setText("Marca:");

        b_guardarR.setText("Guardar");
        b_guardarR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarRMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tf_tamañoR, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tf_marcaR))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(b_guardarR)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_tamañoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_marcaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(b_guardarR)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("RAM", jPanel1);

        jLabel6.setText("Tamaño:");

        jLabel7.setText("Marca:");

        b_guardarDD.setText("Guardar");
        b_guardarDD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarDDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(tf_tamañoDD, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tf_marcaDD, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(b_guardarDD)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_tamañoDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_marcaDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(b_guardarDD)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DiscoD", jPanel2);

        jLabel8.setText("Horas:");

        jLabel9.setText("Materiañ:");

        tf_materialB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_materialBActionPerformed(evt);
            }
        });

        b_guardarB.setText("Guardar");
        b_guardarB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_CapicidadB)
                            .addComponent(tf_materialB, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(b_guardarB)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_CapicidadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_materialB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(b_guardarB)
                .addGap(63, 63, 63))
        );

        jTabbedPane1.addTab("Bateria", jPanel3);

        jLabel10.setText("Material:");

        jLabel11.setText("Color:");

        b_guardarT.setText("Guardar");
        b_guardarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarTMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_guardarT)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(tf_materialT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(tf_colorT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_materialT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_colorT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(b_guardarT)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Teclado", jPanel4);

        jLabel12.setText("Tipo:");

        jLabel13.setText("Tactil");

        chb_tactil.setText("Si");

        b_guardarP.setText("Guardar");
        b_guardarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_guardarP)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(tf_tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(18, 18, 18)
                            .addComponent(chb_tactil))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_tipoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(chb_tactil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(b_guardarP)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Pantalla", jPanel5);

        jLabel14.setText("Nucleos:");

        jLabel15.setText("Velocidad:");

        b_guardarPr.setText("Guardar");
        b_guardarPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_guardarPrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tf_velocidadPr))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nucleosPr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(b_guardarPr)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_nucleosPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_velocidadPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(b_guardarPr)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Procesador", jPanel6);

        jLabel2.setText("Menu Partes");

        jLabel3.setText("Tiempo:");

        javax.swing.GroupLayout jf_MenuPartesLayout = new javax.swing.GroupLayout(jf_MenuPartes.getContentPane());
        jf_MenuPartes.getContentPane().setLayout(jf_MenuPartesLayout);
        jf_MenuPartesLayout.setHorizontalGroup(
            jf_MenuPartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MenuPartesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jf_MenuPartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuPartesLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(tf_TiempoE, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(jf_MenuPartesLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jf_MenuPartesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jf_MenuPartesLayout.setVerticalGroup(
            jf_MenuPartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuPartesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jf_MenuPartesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_TiempoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setText("Menu COmputadoras");

        jLabel17.setText("# Serie:");

        jLabel18.setText("Año:");

        jLabel19.setText("Color:");

        jLabel20.setText("Material:");

        jLabel21.setText("RAM:");

        jLabel22.setText("DiscoD:");

        jLabel23.setText("Bateria:");

        jLabel24.setText("Teclado:");

        jLabel25.setText("Pantalla:");

        jLabel26.setText("Procesador:");

        b_listacomp.setText("Listo");
        b_listacomp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_listacompMouseClicked(evt);
            }
        });

        tablaOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza", "Ensamblado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaOrden);
        if (tablaOrden.getColumnModel().getColumnCount() > 0) {
            tablaOrden.getColumnModel().getColumn(0).setResizable(false);
            tablaOrden.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel27.setText("Tecnico:");

        cb_Computadoras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ComputadorasItemStateChanged(evt);
            }
        });

        b_modComps.setText("Modificar");
        b_modComps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_modCompsMouseClicked(evt);
            }
        });

        b_elimcomp.setText("Eliminar");
        b_elimcomp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_elimcompMouseClicked(evt);
            }
        });

        b_ensamblarComp.setText("Ensamblar");
        b_ensamblarComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ensamblarCompMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_MenuComputadorasLayout = new javax.swing.GroupLayout(jf_MenuComputadoras.getContentPane());
        jf_MenuComputadoras.getContentPane().setLayout(jf_MenuComputadorasLayout);
        jf_MenuComputadorasLayout.setHorizontalGroup(
            jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_NumeroSerieC))
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel16)
                                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_añoC, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27))
                            .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(b_listacomp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(27, 27, 27)
                                        .addComponent(tf_materialC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuComputadorasLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuComputadorasLayout.createSequentialGroup()
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addComponent(b_elimcomp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b_ensamblarComp))
                                    .addComponent(barra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_Computadoras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addComponent(b_modComps)
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(103, 103, 103))))
                    .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_colorC, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jf_MenuComputadorasLayout.createSequentialGroup()
                            .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cb_RAM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_DIscoD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_Bateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_teclado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_pantalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jf_MenuComputadorasLayout.setVerticalGroup(
            jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(tf_NumeroSerieC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(tf_añoC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(tf_colorC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_materialC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_MenuComputadorasLayout.createSequentialGroup()
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(cb_RAM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(cb_DIscoD, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(cb_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cb_teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(cb_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(cb_procesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(b_listacomp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cb_Computadoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cb_tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27)))
                                    .addGroup(jf_MenuComputadorasLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(b_modComps)))))))
                .addGap(18, 18, 18)
                .addGroup(jf_MenuComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_elimcomp)
                    .addComponent(b_ensamblarComp))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel28.setText("Menu Tecnico");

        jLabel29.setText("Nombre:");

        jLabel30.setText("Años:");

        tf_edadTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_edadTecActionPerformed(evt);
            }
        });

        jLabel31.setText("Genero:");

        buttonGroup1.add(rd_M);
        rd_M.setSelected(true);
        rd_M.setText("M");

        buttonGroup1.add(rd_F);
        rd_F.setText("F");

        b_crearTec.setText("Crear");
        b_crearTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_crearTecMouseClicked(evt);
            }
        });

        cb_tecnicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tecnicosItemStateChanged(evt);
            }
        });

        b_modTec.setText("Modificar");
        b_modTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_modTecMouseClicked(evt);
            }
        });

        b_EliminarTec.setText("Eliminar");
        b_EliminarTec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_EliminarTecMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jf_MenuTecnicosLayout = new javax.swing.GroupLayout(jf_MenuTecnicos.getContentPane());
        jf_MenuTecnicos.getContentPane().setLayout(jf_MenuTecnicosLayout);
        jf_MenuTecnicosLayout.setHorizontalGroup(
            jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_crearTec)
                            .addComponent(rd_M)))
                    .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                        .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombreTec, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rd_F)
                                .addComponent(tf_edadTec, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_modTec)
                    .addComponent(b_EliminarTec))
                .addGap(57, 57, 57))
        );
        jf_MenuTecnicosLayout.setVerticalGroup(
            jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(26, 26, 26)
                .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_nombreTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_edadTec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(rd_M)
                            .addComponent(rd_F)))
                    .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(b_modTec)))
                .addGroup(jf_MenuTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(b_crearTec))
                    .addGroup(jf_MenuTecnicosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(b_EliminarTec)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Principal");

        b_menupartes.setText("Menu Partes");
        b_menupartes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menupartesMouseClicked(evt);
            }
        });

        b_menuComps.setText("Menu Computadoras");
        b_menuComps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menuCompsMouseClicked(evt);
            }
        });

        b_menuTecni.setText("Menu Tecnicos");
        b_menuTecni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_menuTecniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_menuTecni)
                    .addComponent(b_menuComps)
                    .addComponent(b_menupartes)
                    .addComponent(jLabel1))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(b_menupartes)
                .addGap(39, 39, 39)
                .addComponent(b_menuComps)
                .addGap(44, 44, 44)
                .addComponent(b_menuTecni)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_menupartesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menupartesMouseClicked
        // TODO add your handling code here:
        jf_MenuPartes.setVisible(true);
        try {
            CargarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_menupartesMouseClicked

    private void b_menuCompsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menuCompsMouseClicked
        // TODO add your handling code here:
        jf_MenuComputadoras.setVisible(true);
        try {
            CargarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_menuCompsMouseClicked

    private void b_menuTecniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_menuTecniMouseClicked
        // TODO add your handling code here:
        jf_MenuTecnicos.setVisible(true);
        try {
            CargarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_menuTecniMouseClicked


    private void tf_edadTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_edadTecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_edadTecActionPerformed

    private void tf_materialBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_materialBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_materialBActionPerformed

    private void b_guardarRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarRMouseClicked
        String marca;
        int tamaño, tiempo;
        try {
            tiempo = Integer.parseInt(tf_TiempoE.getText());
            tamaño = Integer.parseInt(tf_tamañoR.getText());
            marca = tf_marcaR.getText();
            parte.add(new RAM(tamaño, marca, tiempo));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_guardarRMouseClicked

    private void b_guardarDDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarDDMouseClicked
        // TODO add your handling code here:
        String marca;
        int tamaño, tiempo;
        try {
            tiempo = Integer.parseInt(tf_TiempoE.getText());
            tamaño = Integer.parseInt(tf_tamañoDD.getText());
            marca = tf_marcaDD.getText();
            parte.add(new DiscoDuro(tamaño, marca, tiempo));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_guardarDDMouseClicked

    private void b_guardarBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarBMouseClicked
        // TODO add your handling code here:
        String material;
        int horas, tiempo;
        try {
            tiempo = Integer.parseInt(tf_TiempoE.getText());
            horas = Integer.parseInt(tf_CapicidadB.getText());
            material = tf_materialB.getText();
            parte.add(new Bateria(horas, material, tiempo));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_guardarBMouseClicked

    private void b_guardarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarTMouseClicked
        // TODO add your handling code here:
        String material, color;
        int tiempo;
        try {
            tiempo = Integer.parseInt(tf_TiempoE.getText());
            color = tf_tamañoR.getText();
            material = tf_materialT.getText();
            parte.add(new Teclado(material, color, tiempo));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_guardarTMouseClicked

    private void b_guardarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarPMouseClicked
        // TODO add your handling code here:
        String tipo;
        boolean tactil = false;
        int tiempo;
        try {
            tiempo = Integer.parseInt(tf_TiempoE.getText());
            tipo = tf_tipoP.getText();
            if (chb_tactil.isSelected()) {
                tactil = true;
            }
            parte.add(new Pantalla(tactil, tipo, tiempo));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_guardarPMouseClicked

    private void b_guardarPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_guardarPrMouseClicked
        // TODO add your handling code here:
        double velocidad;
        int nucleos, tiempo;
        try {
            tiempo = Integer.parseInt(tf_TiempoE.getText());
            velocidad = Double.parseDouble(tf_velocidadPr.getText());
            nucleos = Integer.parseInt(tf_nucleosPr.getText());
            parte.add(new Procesador(nucleos, velocidad, tiempo));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_guardarPrMouseClicked

    private void b_crearTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_crearTecMouseClicked
        // TODO add your handling code here:
        String nombre, genero;
        int edad;
        try {
            nombre = tf_nombreTec.getText();
            if (rd_M.isSelected()) {
                genero = "Masculino";
            } else {
                genero = "Femenino";
            }
            edad = Integer.parseInt(tf_edadTec.getText());
            tecni.add(new Tecnicos(nombre, edad, genero));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_crearTecMouseClicked

    private void cb_tecnicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tecnicosItemStateChanged
        // TODO add your handling code here:
        /*
        try {
            Tecnicos tectemp = (Tecnicos) cb_tecnicos.getSelectedItem();
            tf_nombreTec.setText(tectemp.getNombreT()+ "");
            tf_edadTec.setText(tectemp.getEdadT() + "");
            if (tectemp.getGenero().equals("Masculino")) {
                rd_M.setSelected(true);
            } else {
                rd_M.setSelected(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Algo salió mal");
        }
*/

    }//GEN-LAST:event_cb_tecnicosItemStateChanged

    private void b_modTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_modTecMouseClicked
        // TODO add your handling code here:
        int flag = cb_tecnicos.getSelectedIndex();
        String nombre, genero;
        int edad;
        try {
            nombre = tf_nombreTec.getText();
            if (rd_M.isSelected()) {
                genero = "Masculino";
            } else {
                genero = "Femenino";
            }
            edad = Integer.parseInt(tf_edadTec.getText());
            tecni.get(flag).setNombreT(nombre);
            tecni.get(flag).setEdadT(edad);
            tecni.get(flag).setGenero(genero);
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_modTecMouseClicked

    private void b_EliminarTecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_EliminarTecMouseClicked
        // TODO add your handling code here:
        try {
            int flag = cb_tecnicos.getSelectedIndex();
            tecni.remove(flag);
            ActualizarCombox();
            JOptionPane.showMessageDialog(this, "Eliminado con exito");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error algo salio mal");
        }
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_b_EliminarTecMouseClicked

    private void b_listacompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_listacompMouseClicked
        // TODO add your handling code here:
        int serie, año;
        String color, material;
        RAM ram;
        DiscoDuro discod;
        Bateria bateria;
        Teclado teclado;
        Pantalla pantalla;
        Procesador procesador;
        try {
            serie = Integer.parseInt(tf_NumeroSerieC.getText());
            año = Integer.parseInt(tf_añoC.getText());
            color = tf_colorC.getText();
            material = tf_materialC.getText();
            ram = (RAM) cb_RAM.getSelectedItem();
            discod = (DiscoDuro) cb_DIscoD.getSelectedItem();
            bateria = (Bateria) cb_Bateria.getSelectedItem();
            teclado = (Teclado) cb_teclado.getSelectedItem();
            pantalla = (Pantalla) cb_pantalla.getSelectedItem();
            procesador = (Procesador) cb_procesador.getSelectedItem();
            comp.add(new Computadora(serie, año, color, material, ram, discod, bateria, teclado, pantalla, procesador));
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_listacompMouseClicked

    private void b_modCompsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_modCompsMouseClicked
        // TODO add your handling code here:
        int serie, año, flag = cb_Computadoras.getSelectedIndex();
        String color, material;
        RAM ram;
        DiscoDuro discod;
        Bateria bateria;
        Teclado teclado;
        Pantalla pantalla;
        Procesador procesador;
        try {
            serie = Integer.parseInt(tf_NumeroSerieC.getText());
            año = Integer.parseInt(tf_añoC.getText());
            color = tf_colorC.getText();
            material = tf_materialC.getText();
            ram = (RAM) cb_RAM.getSelectedItem();
            discod = (DiscoDuro) cb_DIscoD.getSelectedItem();
            bateria = (Bateria) cb_Bateria.getSelectedItem();
            teclado = (Teclado) cb_teclado.getSelectedItem();
            pantalla = (Pantalla) cb_pantalla.getSelectedItem();
            procesador = (Procesador) cb_procesador.getSelectedItem();
            Computadora temp = new Computadora(serie, año, color, material, ram, discod, bateria, teclado, pantalla, procesador);
            comp.set(flag, temp);
            JOptionPane.showMessageDialog(this, "Guardado con exito");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error!");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_modCompsMouseClicked

    private void b_elimcompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_elimcompMouseClicked
        // TODO add your handling code here:
        try {
            int flag = cb_Computadoras.getSelectedIndex();
            comp.remove(flag);
            JOptionPane.showMessageDialog(this, "Eliminado con exito!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error grave detectado");
        }
        ActualizarCombox();
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_elimcompMouseClicked

    private void b_ensamblarCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ensamblarCompMouseClicked
        // TODO add your handling code here:
        try {
            int flag = cb_Computadoras.getSelectedIndex();
            Computadora temp = (Computadora) cb_Computadoras.getSelectedItem();
            Tecnicos temptec = (Tecnicos) cb_tecnico.getSelectedItem();
            orden.add(new OrdenEnsamblaje(temp, temptec));
            comp.remove(flag);
            JOptionPane.showMessageDialog(this, "Ensamblando");
            simulacion(temp, temptec);
            ActualizarCombox();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error grave detectado!");
        }
        try {
            GuardarTodo();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_ensamblarCompMouseClicked

    private void cb_ComputadorasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ComputadorasItemStateChanged
        // TODO add your handling code here:
        try {
            Computadora temp = (Computadora) cb_Computadoras.getSelectedItem();
            tf_NumeroSerieC.setText(temp.getNumeroSerieC() + "");
            tf_añoC.setText(temp.getAñoC() + "");
            tf_colorC.setText(temp.getColor());
            tf_materialC.setText(temp.getMaterialC());
            cb_RAM.setSelectedItem(temp.getRamC());
            cb_DIscoD.setSelectedItem(temp.getDiscoduroC());
            cb_Bateria.setSelectedItem(temp.getBateriaC());
            cb_teclado.setSelectedItem(temp.getTecladoC());
            cb_pantalla.setSelectedItem(temp.getPantallaC());
            cb_procesador.setSelectedItem(temp.getProcesadorC());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cb_ComputadorasItemStateChanged

    public void simulacion(Computadora comp, Tecnicos tec) {
        
        boolean flag = true;
        DefaultTableModel modelo
                = (DefaultTableModel) tablaOrden.getModel();
        while (flag == true) {
            
            AdministrarBarra abr = new AdministrarBarra(barra, comp.getRamC().getMin());
            abr.run();
            while (!abr.isAlive()) {
                System.out.println("entra1");
                Object[] newrow = {
                    "RAM",
                    "COMPLETO"};
                modelo.addRow(newrow);
                tablaOrden.setModel(modelo);
                AdministrarBarra abd = new AdministrarBarra(barra, comp.getDiscoduroC().getMin());
                abd.run();
                while (!abd.isAlive()) {
                    System.out.println("entra2");
                    Object[] newrow2 = {
                        "DISCO DURO",
                        "COMPLETO"};
                    modelo.addRow(newrow2);
                    tablaOrden.setModel(modelo);
                    AdministrarBarra abb = new AdministrarBarra(barra, comp.getBateriaC().getMin());
                    abb.run();
                    while (!abb.isAlive()) {
                        System.out.println("entra3");
                        Object[] newrow3 = {
                            "BATERIA",
                            "COMPLETO"};
                        modelo.addRow(newrow);
                        tablaOrden.setModel(modelo);
                        AdministrarBarra abt = new AdministrarBarra(barra, comp.getTecladoC().getMin());
                        abt.run();
                        while (!abt.isAlive()) {
                            System.out.println("entra4");
                            Object[] newrow4 = {
                                "TECLADO",
                                "COMPLETO"};
                            modelo.addRow(newrow);
                            tablaOrden.setModel(modelo);
                            AdministrarBarra abp = new AdministrarBarra(barra, comp.getPantallaC().getMin());
                            abp.run();
                            while (!abp.isAlive()) {
                                System.out.println("entra5");
                                Object[] newrow5 = {
                                    "PANTALLA",
                                    "COMPLETO"};
                                modelo.addRow(newrow);
                                tablaOrden.setModel(modelo);
                                AdministrarBarra abpr = new AdministrarBarra(barra, comp.getProcesadorC().getMin());
                                abpr.run();
                                while (!abpr.isAlive()) {
                                    System.out.println("entra6");
                                    Object[] newrow6 = {
                                        "PROCESADOR",
                                        "COMPLETO"};
                                    modelo.addRow(newrow);
                                    tablaOrden.setModel(modelo);
                                    flag = false;
                                    break;
                                }
                               break; 
                            }
                           break; 
                        }
                        break;
                    }
                    break;
                }
                break;
            }
            break;
        }
        fallar(comp, tec);

    }

    public void fallar(Computadora comp, Tecnicos tecni) {
        int flag = tecni.getComputadorasT(), num = ran.nextInt(100);

        if (flag < 6) {
            if (num < 30) {
                informe(comp.toString(), tecni.toString());
            }
        } else if (flag > 5 && flag < 16) {
            if (num < 22) {
                informe(comp.toString(), tecni.toString());
            }
        } else if (flag > 15 && flag < 31) {
            if (num < 13) {
                informe(comp.toString(), tecni.toString());
            }
        } else {
            if (num < 7) {
                informe(comp.toString(), tecni.toString());
            }
        }
    }

    public void informe(String comp, String tecni) {
        File f = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            f = new File("./fallos.txt");
            fw = new FileWriter(f, true); //OJO 
            bw = new BufferedWriter(fw);
            String u, p, r;
            u = comp;
            p = tecni;
            bw.write(u + "/");
            bw.write(p + "/");
            bw.flush();

        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void GuardarTec() {
        File f = null;
        FileWriter fw = null;
        BufferedWriter bw = null;
        for (int i = 0; i < tecni.size(); i++) {
            try {
                f = new File("./tecnicos.txt");
                fw = new FileWriter(f, true); //OJO 
                bw = new BufferedWriter(fw);
                String u, p, r;
                int e, c;
                u = tecni.get(i).getNombreT();
                e = tecni.get(i).getEdadT();
                p = tecni.get(i).getGenero();
                c = tecni.get(i).getComputadorasT();
                bw.write(u + "/");
                bw.write(e + "/");
                bw.write(p + "/");
                bw.write(c + "/");
                bw.flush();

            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void CargarTec() throws IOException {
        File f = null;
        FileReader fr = null;
        BufferedReader br = null;
        try {
            f = new File("./tecnicos.txt");
            fr = new FileReader(f);
            br = new BufferedReader(fr);
            String linea;
            String[] tokens;
            while ((linea = br.readLine()) != null) {
                tokens = linea.split("/");
                tecni.add(new Tecnicos(tokens[0], Integer.parseInt(tokens[1]), tokens[2]));
                tokens = null;
            }

        } catch (Exception e) {
            e.printStackTrace();

        }
        br.close();
        fr.close();
    }

    public void CargarTodo() throws IOException {
        if (cargado == false) {
            System.out.println("Cargando");
            CargarTec();
            AdminComputadora ac = new AdminComputadora("./ficheros/computadora.tcr");
            AdminPartes ap = new AdminPartes("./ficheros/partes.tcr");
            ac.cargarArchivo();
            ap.cargarArchivo();
            comp = ac.getListaC();
            parte = ap.getListaP();
            ActualizarCombox();
            cargado = true;
            System.out.println("Cargó");
        }
    }

    public void GuardarTodo() throws IOException {
        GuardarTec();
        AdminComputadora ac = new AdminComputadora("./ficheros/computadora.tcr");
        AdminPartes ap = new AdminPartes("./ficheros/partes.tcr");
        ac.cargarArchivo();
        for (int i = 0; i < comp.size(); i++) {
            ac.setComp(comp.get(i));
        }
        ac.escribirArchivo();
        ap.cargarArchivo();
        for (int i = 0; i < parte.size(); i++) {
            ap.setPartes(parte.get(i));
        }
        ap.escribirArchivo();
        ActualizarCombox();
    }

    public void ActualizarCombox() {
        try {
            DefaultComboBoxModel lcomp = (DefaultComboBoxModel) cb_Computadoras.getModel();
            DefaultComboBoxModel ltecni = (DefaultComboBoxModel) cb_tecnicos.getModel();
            DefaultComboBoxModel ltecni2 = (DefaultComboBoxModel) cb_tecnico.getModel();
            DefaultComboBoxModel lbate = (DefaultComboBoxModel) cb_Bateria.getModel();
            DefaultComboBoxModel ldisco = (DefaultComboBoxModel) cb_DIscoD.getModel();
            DefaultComboBoxModel lram = (DefaultComboBoxModel) cb_RAM.getModel();
            DefaultComboBoxModel lpan = (DefaultComboBoxModel) cb_pantalla.getModel();
            DefaultComboBoxModel lpro = (DefaultComboBoxModel) cb_procesador.getModel();
            DefaultComboBoxModel ltecl = (DefaultComboBoxModel) cb_teclado.getModel();

            lcomp.removeAllElements();
            lbate.removeAllElements();
            ldisco.removeAllElements();
            lpan.removeAllElements();
            lpro.removeAllElements();
            lram.removeAllElements();
            ltecl.removeAllElements();
            ltecni.removeAllElements();
            ltecni2.removeAllElements();

            for (int i = 0; i < comp.size(); i++) {
                lcomp.addElement(comp.get(i));
            }

            for (int i = 0; i < tecni.size(); i++) {
                ltecni.addElement(tecni.get(i));
                ltecni2.addElement(tecni.get(i));
            }

            for (int i = 0; i < parte.size(); i++) {
                if (parte.get(i) instanceof Bateria) {
                    lbate.addElement(parte.get(i));
                } else if (parte.get(i) instanceof DiscoDuro) {
                    ldisco.addElement(parte.get(i));
                } else if (parte.get(i) instanceof RAM) {
                    lram.addElement(parte.get(i));
                } else if (parte.get(i) instanceof Pantalla) {
                    lpan.addElement(parte.get(i));
                } else if (parte.get(i) instanceof Procesador) {
                    lpro.addElement(parte.get(i));
                } else if (parte.get(i) instanceof Teclado) {
                    ltecl.addElement(parte.get(i));
                };
            }
            cb_Bateria.setModel(lbate);
            cb_Computadoras.setModel(lcomp);
            cb_DIscoD.setModel(ldisco);
            cb_RAM.setModel(lram);
            cb_pantalla.setModel(lpan);
            cb_procesador.setModel(lpro);
            cb_teclado.setModel(ltecl);
            cb_tecnico.setModel(ltecni);
            cb_tecnicos.setModel(ltecni2);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_EliminarTec;
    private javax.swing.JButton b_crearTec;
    private javax.swing.JButton b_elimcomp;
    private javax.swing.JButton b_ensamblarComp;
    private javax.swing.JButton b_guardarB;
    private javax.swing.JButton b_guardarDD;
    private javax.swing.JButton b_guardarP;
    private javax.swing.JButton b_guardarPr;
    private javax.swing.JButton b_guardarR;
    private javax.swing.JButton b_guardarT;
    private javax.swing.JButton b_listacomp;
    private javax.swing.JButton b_menuComps;
    private javax.swing.JButton b_menuTecni;
    private javax.swing.JButton b_menupartes;
    private javax.swing.JButton b_modComps;
    private javax.swing.JButton b_modTec;
    private javax.swing.JProgressBar barra;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_Bateria;
    private javax.swing.JComboBox<String> cb_Computadoras;
    private javax.swing.JComboBox<String> cb_DIscoD;
    private javax.swing.JComboBox<String> cb_RAM;
    private javax.swing.JComboBox<String> cb_pantalla;
    private javax.swing.JComboBox<String> cb_procesador;
    private javax.swing.JComboBox<String> cb_teclado;
    private javax.swing.JComboBox<String> cb_tecnico;
    private javax.swing.JComboBox<String> cb_tecnicos;
    private javax.swing.JCheckBox chb_tactil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JFrame jf_MenuComputadoras;
    private javax.swing.JFrame jf_MenuPartes;
    private javax.swing.JFrame jf_MenuTecnicos;
    private javax.swing.JRadioButton rd_F;
    private javax.swing.JRadioButton rd_M;
    private javax.swing.JTable tablaOrden;
    private javax.swing.JTextField tf_CapicidadB;
    private javax.swing.JTextField tf_NumeroSerieC;
    private javax.swing.JTextField tf_TiempoE;
    private javax.swing.JTextField tf_añoC;
    private javax.swing.JTextField tf_colorC;
    private javax.swing.JTextField tf_colorT;
    private javax.swing.JTextField tf_edadTec;
    private javax.swing.JTextField tf_marcaDD;
    private javax.swing.JTextField tf_marcaR;
    private javax.swing.JTextField tf_materialB;
    private javax.swing.JTextField tf_materialC;
    private javax.swing.JTextField tf_materialT;
    private javax.swing.JTextField tf_nombreTec;
    private javax.swing.JTextField tf_nucleosPr;
    private javax.swing.JTextField tf_tamañoDD;
    private javax.swing.JTextField tf_tamañoR;
    private javax.swing.JTextField tf_tipoP;
    private javax.swing.JTextField tf_velocidadPr;
    // End of variables declaration//GEN-END:variables
    ArrayList<Computadora> comp = new ArrayList();
    ArrayList<Tecnicos> tecni = new ArrayList();
    ArrayList<OrdenEnsamblaje> orden = new ArrayList();
    ArrayList<Parte> parte = new ArrayList();
    Random ran = new Random();
    boolean cargado = false;
}
